apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    addonmanager.kubernetes.io/mode: Reconcile
    cryptophys.io/flux-managed: 'true'
    kubernetes.io/cluster-service: 'true'
  name: node-local-dns
  namespace: kube-system
