apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cerebrum-observer
  labels:
    app: cerebrum
    cryptophys.io/domain: cerebrum
    cryptophys.io/component: observer
rules:
  - apiGroups: [""]
    resources:
      - pods
      - services
      - namespaces
    verbs:
      - get
      - list
      - watch
  - apiGroups: ["apps"]
    resources:
      - deployments
      - replicasets
      - statefulsets
    verbs:
      - get
      - list
      - watch
  - apiGroups: ["ray.io"]
    resources:
      - rayclusters
    verbs:
      - get
      - list
      - watch
