---
apiVersion: kyverno.io/v2
kind: PolicyException
metadata:
  name: kyverno-command-center-exception
  namespace: kyverno-system
spec:
  exceptions:
    - policyName: cp-standard-naming-v1
      ruleNames:
        - validate-resource-name
    - policyName: cp-supplychain-registry-v1
      ruleNames:
        - restrict-image-registries
  match:
    any:
      - resources:
          kinds:
            - Deployment
            - Pod
          namespaces:
            - kyverno-system
          names:
            - kyverno-command-center*
