apiVersion: cryptophys.work/v1alpha1
kind: LonghornRelease
metadata:
  name: longhorn
  namespace: crossplane-system
spec:
  defaultReplicaCount: 2
  taintToleration: "node-role.kubernetes.io/control-plane:NoSchedule;daemonset=true:NoSchedule;cryptophys.io/pool=platform-ha:NoSchedule;ray-cluster=true:NoSchedule;ray-head=true:NoSchedule;bridge-system=true:NoSchedule;dao-system=true:NoSchedule;node.kubernetes.io/memory-pressure:NoSchedule"
  storageOverProvisioningPercentage: 150
  storageMinimalAvailablePercentage: 15
  concurrentReplicaRebuildPerNodeLimit: 2
  guaranteedInstanceManagerCPU: 0.25
  systemManagedComponentsNodeSelector: ""
  managerResources:
    requests:
      cpu: 200m
      memory: 512Mi
    limits:
      cpu: 1000m
      memory: 512Mi
