apiVersion: cryptophys.work/v1alpha1
kind: LonghornRelease
metadata:
  name: longhorn
  namespace: crossplane-system
spec:
  defaultReplicaCount: 2
  taintToleration: "cryptophys.io/storage-only=true:NoSchedule;cryptophys.io/role=llm-inference:NoSchedule"
  managerResources:
    requests:
      cpu: 200m
      memory: 512Mi
    limits:
      cpu: 1000m
      memory: 2Gi
