apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitea-redis
  namespace: gitops-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gitea-redis
  template:
    metadata:
      labels:
        app: gitea-redis
    spec:
      containers:
      - name: redis
        image: redis:7.2-alpine
        ports:
        - containerPort: 6379
        resources:
          requests:
            cpu: 50m
            memory: 64Mi
          limits:
            cpu: 200m
            memory: 256Mi
---
apiVersion: v1
kind: Service
metadata:
  name: gitea-redis
  namespace: gitops-system
spec:
  selector:
    app: gitea-redis
  ports:
  - protocol: TCP
    port: 6379
    targetPort: 6379
