apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: gitea-postgres-egress
  namespace: gitops-system
  labels:
    app.kubernetes.io/name: gitea
    app.kubernetes.io/instance: gitops-gitea
    cryptophys.io/domain: platform
    cryptophys.io/component: gitea
    cryptophys.io/managed-by: flux
    cryptophys.io/layer: platform
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: gitea
      app.kubernetes.io/instance: gitops-gitea
  policyTypes:
    - Egress
  egress:
    - to:
        - ipBlock:
            cidr: 10.96.0.10/32
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: kube-system
          podSelector:
            matchLabels:
              k8s-app: kube-dns
      ports:
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 53
    - to:
        - ipBlock:
            cidr: 10.96.212.41/32
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: postgresql-system
          podSelector:
            matchExpressions:
              - key: cnpg.io/cluster
                operator: In
                values:
                  - postgres-security-ha
                  - postgres-security-ha
      ports:
        - protocol: TCP
          port: 5432
    - to:
        - ipBlock:
            cidr: 10.100.187.251/32
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: gitops-system
          podSelector:
            matchLabels:
              app: gitea-redis
      ports:
        - protocol: TCP
          port: 6379
