apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: platform-code-forge-gitea
  namespace: gitops-system
spec:
  interval: 30m
  releaseName: platform-code-forge-gitea
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  chart:
    spec:
      chart: gitea
      version: 12.5.0
      sourceRef:
        kind: HelmRepository
        name: gitea-charts
        namespace: flux-system
  values:
    replicaCount: 1
    image:
      registry: ghcr.io
      repository: go-gitea/gitea
      tag: "1.25.4"
      rootless: true
    gitea:
      admin:
        existingSecret: gitea-admin-secret
      config:
        database:
          DB_TYPE: postgres
          HOST: postgres-apps-ha-rw.postgresql-system.svc.cluster.local:5432
          NAME: app
          USER: app
          PASSWD: uA8NrQUOb9no2hg9BGEDFulmlkRlHMK5dAhKwpkm3sozTH43p1UAc9zERIfljQIp
    extraConfig: |
      [cache]
      ADAPTER = redis
      HOST = gitea-redis.gitops-system.svc.cluster.local:6379
      [session]
      PROVIDER = redis
      PROVIDER_CONFIG = redis://gitea-redis.gitops-system.svc.cluster.local:6379/0
      [queue]
      TYPE = redis
      CONN_STR = redis://gitea-redis.gitops-system.svc.cluster.local:6379/1
    ingress:
      enabled: true
      className: nginx
      hosts:
        - host: gitea.cryptophys.work
          paths:
            - path: /
              pathType: Prefix
      tls:
        - secretName: cryptophys-wildcard-tls
          hosts:
            - gitea.cryptophys.work
    persistence:
      enabled: true
      claimName: gitea-shared-storage-rwx
      accessModes:
        - ReadWriteMany
    valkey-cluster:
      enabled: false
    resources:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        cpu: 500m
        memory: 1Gi
