apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitea-redis
  namespace: gitops-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gitea-redis
  template:
    metadata:
      labels:
        app: gitea-redis
    spec:
      tolerations:
      containers:
      - name: redis
        image: redis:7.2-alpine
        ports:
        - containerPort: 6379
        resources:
          requests:
            cpu: 50m
            memory: 64Mi
          limits:
            cpu: 200m
            memory: 256Mi
---
apiVersion: v1
kind: Service
metadata:
  name: gitea-redis
  namespace: gitops-system
spec:
  selector:
    app: gitea-redis
  ports:
  - protocol: TCP
    port: 6379
    targetPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: gitops-gitea-valkey-cluster
  namespace: gitops-system
spec:
  selector:
    app: gitea-redis
  ports:
  - protocol: TCP
    port: 6379
    targetPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: gitops-gitea-valkey-cluster-headless
  namespace: gitops-system
spec:
  clusterIP: None
  selector:
    app: gitea-redis
  ports:
  - name: tcp-valkey
    protocol: TCP
    port: 6379
    targetPort: 6379
  - name: tcp-valkey-bus
    protocol: TCP
    port: 16379
    targetPort: 16379
