apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - platform__gitea_http_internal_service.yaml
  - platform__gitea_shared_storage_rwx_pvc.yaml
  - platform__gitea_shared_storage_rwx_migration_job.yaml
  - gitea-redis.yaml
  - gitea-platform.yaml
  - platform__gitea_picoclaw_guard_script.yaml
  - gitea-postgres-egress-netpol.yaml
  - gitea-internal-mtls.yaml
  - gitea-internal-cnp.yaml
