apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitea-shared-storage-rwx
  namespace: gitops-system
  labels:
    app.kubernetes.io/name: gitops-gitea
    app.kubernetes.io/component: storage
    cryptophys.io/domain: platform
    cryptophys.io/component: gitea
    cryptophys.io/layer: platform
    cryptophys.io/managed-by: flux
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: longhorn-single
  volumeMode: Filesystem
