apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: minio-s3-credentials
  namespace: postgresql-system
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: postgres-backup-secret
    creationPolicy: Owner
    template:
      data:
        ACCESS_KEY_ID: "{{ .rootUser }}" # gitleaks:allow
        ACCESS_SECRET_KEY: "{{ .rootPassword }}" # gitleaks:allow
  data:
    - secretKey: rootUser
      remoteRef:
        key: apps/minio/admin
        property: rootUser
    - secretKey: rootPassword
      remoteRef:
        key: apps/minio/admin
        property: rootPassword
