apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  annotations: {}
  name: postgres-ha
  namespace: postgresql-system
spec:
  affinity:
    nodeSelector:
      cryptophys.io/tier: platform
    podAntiAffinityType: required
    tolerations:
    - effect: NoSchedule
      key: node-role.kubernetes.io/control-plane
    topologyKey: kubernetes.io/hostname
  backup:
    barmanObjectStore:
      destinationPath: s3://postgres-backups/
      s3Credentials:
        accessKeyId:
          key: ACCESS_KEY_ID
          name: postgres-backup-secret
        secretAccessKey:
          key: ACCESS_SECRET_KEY
          name: postgres-backup-secret
      wal:
        compression: gzip
        maxParallel: 8
    retentionPolicy: 30d
    target: prefer-standby
  bootstrap:
    initdb:
      database: postgres
      encoding: UTF8
      localeCType: C
      localeCollate: C
      owner: postgres
      postInitSQL:
      - CREATE DATABASE spire;
      - CREATE DATABASE gitea;
      - CREATE DATABASE harbor;
      - CREATE DATABASE registry;
  enablePDB: true
  enableSuperuserAccess: false
  failoverDelay: 0
  imageName: ghcr.io/cloudnative-pg/postgresql:16.2
  instances: 3
  logLevel: info
  maxSyncReplicas: 0
  minSyncReplicas: 0
  monitoring:
    customQueriesConfigMap:
    - key: queries
      name: cnpg-default-monitoring
    disableDefaultQueries: false
    enablePodMonitor: false
  postgresGID: 26
  postgresUID: 26
  postgresql:
    parameters:
      archive_mode: 'on'
      archive_timeout: 5min
      checkpoint_completion_target: '0.9'
      default_statistics_target: '100'
      dynamic_shared_memory_type: posix
      effective_cache_size: 1GB
      effective_io_concurrency: '200'
      full_page_writes: 'on'
      log_destination: csvlog
      log_directory: /controller/log
      log_filename: postgres
      log_rotation_age: '0'
      log_rotation_size: '0'
      log_truncate_on_rotation: 'false'
      logging_collector: 'on'
      maintenance_work_mem: 128MB
      max_connections: '200'
      max_parallel_maintenance_workers: '2'
      max_parallel_workers: '4'
      max_parallel_workers_per_gather: '2'
      max_replication_slots: '32'
      max_wal_size: 4GB
      max_worker_processes: '4'
      min_wal_size: 1GB
      random_page_cost: '1.1'
      shared_buffers: 256MB
      shared_memory_type: mmap
      shared_preload_libraries: ''
      ssl_max_protocol_version: TLSv1.3
      ssl_min_protocol_version: TLSv1.3
      wal_buffers: 16MB
      wal_keep_size: 512MB
      wal_level: logical
      wal_log_hints: 'on'
      wal_receiver_timeout: 5s
      wal_sender_timeout: 5s
      work_mem: 5242kB
    syncReplicaElectionConstraint:
      enabled: false
  primaryUpdateMethod: restart
  primaryUpdateStrategy: unsupervised
  probes:
    liveness:
      isolationCheck:
        connectionTimeout: 1000
        enabled: true
        requestTimeout: 1000
  replicationSlots:
    highAvailability:
      enabled: true
      slotPrefix: _cnpg_
    synchronizeReplicas:
      enabled: true
    updateInterval: 30
  resources:
    limits:
      cpu: '2'
      memory: 4Gi
    requests:
      cpu: 500m
      memory: 1Gi
  smartShutdownTimeout: 180
  startDelay: 3600
  stopDelay: 1800
  storage:
    resizeInUseVolumes: true
    size: 20Gi
    storageClass: longhorn
  switchoverDelay: 3600
  walStorage:
    resizeInUseVolumes: true
    size: 5Gi
    storageClass: longhorn
