apiVersion: v1
items:
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      cryptophys.io/gitops-source: unknown-user
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"app":"helm-controller"},"name":"helm-controller","namespace":"flux-system"},"spec":{"ports":[{"name":"http-prom","port":8080,"protocol":"TCP","targetPort":"http-prom"}],"selector":{"app":"helm-controller"},"type":"ClusterIP"}}
    creationTimestamp: "2026-02-16T15:06:28Z"
    labels:
      app: helm-controller
      cryptophys.io/environment: production
      cryptophys.work/managed-by: aide
    name: helm-controller
    namespace: flux-system
    resourceVersion: "1391099"
    uid: dd93ce1e-abdb-4101-9bba-57d70e68f6bb
  spec:
    clusterIP: 10.106.160.163
    clusterIPs:
    - 10.106.160.163
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - name: http-prom
      port: 8080
      protocol: TCP
      targetPort: http-prom
    selector:
      app: helm-controller
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      cryptophys.io/gitops-source: unknown-user
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"app":"kustomize-controller"},"name":"kustomize-controller","namespace":"flux-system"},"spec":{"ports":[{"name":"http-prom","port":8080,"protocol":"TCP","targetPort":"http-prom"}],"selector":{"app":"kustomize-controller"},"type":"ClusterIP"}}
    creationTimestamp: "2026-02-16T15:06:29Z"
    labels:
      app: kustomize-controller
      cryptophys.io/environment: production
      cryptophys.work/managed-by: aide
    name: kustomize-controller
    namespace: flux-system
    resourceVersion: "1391119"
    uid: aa12613f-44a0-4b27-a5cb-f5995423e718
  spec:
    clusterIP: 10.100.202.121
    clusterIPs:
    - 10.100.202.121
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - name: http-prom
      port: 8080
      protocol: TCP
      targetPort: http-prom
    selector:
      app: kustomize-controller
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      cryptophys.io/gitops-source: unknown-user
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"app":"image-automation-controller"},"name":"image-automation-controller","namespace":"flux-system"},"spec":{"ports":[{"name":"http-prom","port":8080,"protocol":"TCP","targetPort":"http-prom"}],"selector":{"app":"image-automation-controller"},"type":"ClusterIP"}}
    creationTimestamp: "2026-02-16T15:06:29Z"
    labels:
      app: image-automation-controller
      cryptophys.io/environment: production
      cryptophys.work/managed-by: aide
    name: image-automation-controller
    namespace: flux-system
    resourceVersion: "1391136"
    uid: 04b686f5-4c92-44db-80fe-2121d78075f9
  spec:
    clusterIP: 10.106.118.63
    clusterIPs:
    - 10.106.118.63
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - name: http-prom
      port: 8080
      protocol: TCP
      targetPort: http-prom
    selector:
      app: image-automation-controller
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      cryptophys.io/gitops-source: unknown-user
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"app":"image-reflector-controller"},"name":"image-reflector-controller","namespace":"flux-system"},"spec":{"ports":[{"name":"http-prom","port":8080,"protocol":"TCP","targetPort":"http-prom"}],"selector":{"app":"image-reflector-controller"},"type":"ClusterIP"}}
    creationTimestamp: "2026-02-16T15:06:30Z"
    labels:
      app: image-reflector-controller
      cryptophys.io/environment: production
      cryptophys.work/managed-by: aide
    name: image-reflector-controller
    namespace: flux-system
    resourceVersion: "1391149"
    uid: 7efe5661-1829-4764-844e-fb13d29a4717
  spec:
    clusterIP: 10.97.25.7
    clusterIPs:
    - 10.97.25.7
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - name: http-prom
      port: 8080
      protocol: TCP
      targetPort: http-prom
    selector:
      app: image-reflector-controller
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
kind: List
metadata:
  resourceVersion: ""
