cluster:
  id: 1
  name: cryptophys-genesis
clustermesh:
  useAPIServer: true
hubble:
  enabled: true
  relay:
    enabled: true
  ui:
    enabled: true
ipam:
  mode: kubernetes
k8sServiceHost: api.cryptophys.work
k8sServicePort: 6443
kubeProxyReplacement: true
svcSourceRangeCheck: false
hostServices:
  enabled: true
socketLB:
  enabled: true
  hostNamespaceOnly: true
extraConfig: {}
operator:
  replicas: 2
  priorityClassName: system-cluster-critical
encryption:
  enabled: true
  type: wireguard
  nodeEncryption: true
priorityClassName: system-node-critical
bpf:
  policyMapMax: 65536
  mapDynamicSizeRatio: 0.005
resources:
  requests:
    cpu: 100m
    memory: 1Gi
  limits:
    memory: 4Gi
securityContext:
  privileged: true
  capabilities:
    ciliumAgent:
    - CHOWN
    - KILL
    - NET_ADMIN
    - NET_RAW
    - IPC_LOCK
    - SYS_ADMIN
    - SYS_RESOURCE
    - DAC_OVERRIDE
    - FOWNER
    - SETGID
    - SETUID
    cleanCiliumState:
    - NET_ADMIN
    - SYS_ADMIN
    - SYS_RESOURCE
