apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cloudflared-tunnel
  namespace: cloudflare-tunnel
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: cloudflared-tunnel
    creationPolicy: Owner
  data:
    - secretKey: config.yml
      remoteRef:
        key: platform/cloudflare/tunnel
        property: config_yaml
    - secretKey: credentials.json
      remoteRef:
        key: platform/cloudflare/tunnel
        property: credentials_json
