apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: registry-harbor-registry-v3
  namespace: registry-system
  labels:
    app.kubernetes.io/name: harbor
    app.kubernetes.io/component: registry
    app.kubernetes.io/part-of: harbor
    cryptophys.io/domain: platform
    cryptophys.io/component: harbor-registry-storage
    cryptophys.io/managed-by: flux
    cryptophys.io/layer: platform
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: longhorn-single
  volumeMode: Filesystem
