apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - harbor__registry-db-externalsecret.yaml
  - harbor__redis-credentials-externalsecret.yaml
  - harbor__project-reconciler-cronjob.yaml
  - storageclass-longhorn-single.yaml
  - storageclass-longhorn-harbor-retain.yaml
  - harbor__registry-pvc-v3.yaml
  - harbor__external-redis.yaml
  - harbor__migration-repair-job.yaml
  - release.yaml
  - pdb.yaml
  - servicemonitor-harbor.yaml
