apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: registry-harbor-core
  namespace: registry-system
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: harbor
      component: core
      release: registry-harbor
