apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: registry-harbor-core
  namespace: registry-system
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app: harbor
      component: core
      release: registry-harbor
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: registry-harbor-portal
  namespace: registry-system
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app: harbor
      component: portal
      release: registry-harbor
