apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: longhorn-harbor-retain
  annotations:
    cryptophys.io/domain: platform
    cryptophys.io/component: harbor-storage
    cryptophys.io/layer: platform
    cryptophys.io/managed-by: flux
provisioner: driver.longhorn.io
allowVolumeExpansion: true
reclaimPolicy: Retain
volumeBindingMode: Immediate
parameters:
  numberOfReplicas: "3"
  staleReplicaTimeout: "30"
  fromBackup: ""
  fsType: "ext4"
  dataLocality: "disabled"
  unmapMarkSnapChainRemoved: "ignored"
  disableRevisionCounter: "true"
  dataEngine: "v1"
  backupTargetName: "default"
