apiVersion: apps/v1
kind: Deployment
metadata:
  name: kueue-controller-manager
  namespace: kueue-system
  annotations:
    cryptophys.io/domain: platform
    cryptophys.io/component: kueue
    cryptophys.io/managed-by: flux
spec:
  template:
    spec:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              preference:
                matchExpressions:
                  - key: accepts-platform-workloads
                    operator: In
                    values:
                      - "true"
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/os
                    operator: In
                    values:
                      - linux
                  - key: workload.cryptophys.work/platform
                    operator: In
                    values:
                      - "true"
      containers:
        - name: manager
          resources:
            limits:
              cpu: 300m
              memory: 384Mi
            requests:
              cpu: 50m
              memory: 96Mi
