apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: kueue-validating-webhook-configuration
  annotations:
    cryptophys.io/domain: platform
    cryptophys.io/component: kueue
    cryptophys.io/managed-by: flux
webhooks:
  - name: vjob.kb.io
    failurePolicy: Ignore
  - name: vjobset.kb.io
    failurePolicy: Ignore
  - name: vclusterqueue.kb.io
    failurePolicy: Ignore
  - name: vpod.kb.io
    failurePolicy: Ignore
  - name: vdeployment.kb.io
    failurePolicy: Ignore
  - name: vmxjob.kb.io
    failurePolicy: Ignore
  - name: vpaddlejob.kb.io
    failurePolicy: Ignore
  - name: vpytorchjob.kb.io
    failurePolicy: Ignore
  - name: vtfjob.kb.io
    failurePolicy: Ignore
  - name: vxgboostjob.kb.io
    failurePolicy: Ignore
  - name: vmpijob.kb.io
    failurePolicy: Ignore
  - name: vraycluster.kb.io
    failurePolicy: Ignore
  - name: vrayjob.kb.io
    failurePolicy: Ignore
  - name: vstatefulset.kb.io
    failurePolicy: Ignore
  - name: vcohort.kb.io
    failurePolicy: Ignore
  - name: vresourceflavor.kb.io
    failurePolicy: Ignore
  - name: vworkload.kb.io
    failurePolicy: Ignore
