apiVersion: apps/v1
kind: Deployment
metadata:
  name: kueue-controller-manager
  namespace: kueue-system
  annotations:
    cryptophys.io/domain: platform
    cryptophys.io/component: kueue
    cryptophys.io/managed-by: flux
spec:
  template:
    spec:
      tolerations:
        - key: cryptophys.io/pool
          operator: Equal
          value: platform-ha
          effect: NoSchedule
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/os
                    operator: In
                    values:
                      - linux
                  - key: node-role.kubernetes.io/worker
                    operator: Exists
                  - key: kubernetes.io/hostname
                    operator: In
                    values:
                      - thalamus-217-76-59-241
                      - cerebellum-161-97-117-96
      containers:
        - name: manager
          resources:
            limits:
              cpu: 300m
              memory: 384Mi
            requests:
              cpu: 50m
              memory: 96Mi
