apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - kueue-install.yaml
  - kueue-config.yaml

patches:
  - path: kueue-webhook-patch.yaml
    target:
      kind: ValidatingWebhookConfiguration
      name: kueue-validating-webhook-configuration
  - path: kueue-mutating-webhook-patch.yaml
    target:
      kind: MutatingWebhookConfiguration
      name: kueue-mutating-webhook-configuration
  - path: kueue-controller-manager-scheduling-patch.yaml
    target:
      kind: Deployment
      name: kueue-controller-manager
