apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
patches:
- target:
    group: kyverno.io
    version: v1
    kind: ClusterPolicy
    name: cp-supplychain-attestation-v1
  patch: |
    - op: add
      path: /spec/rules/0/exclude/any/-
      value:
        resources:
          namespaces: ["aide"]
- target:
    group: kyverno.io
    version: v1
    kind: ClusterPolicy
    name: cp-supplychain-cosign-enforce-v1
  patch: |
    - op: add
      path: /spec/rules/0/exclude/any/-
      value:
        resources:
          namespaces: ["aide"]
