USER-SUPPLIED VALUES:
defaultSettings:
  defaultReplicaCount: 2
  systemManagedComponentsNodeSelector: "kubernetes.io/os: linux"
  taintToleration: "*"
persistence:
  defaultClass: true
  defaultClassReplicaCount: 2
csi:
  kubeletRootDir: /var/lib/kubelet
longhornCSI:
  tolerations:
    - operator: Exists
longhornUI:
  replicas: 2
  nodeSelector:
    kubernetes.io/os: linux
  tolerations:
    - operator: Exists
  resources:
    requests:
      cpu: 10m
      memory: 64Mi
    limits:
      cpu: 100m
      memory: 256Mi
longhornManager:
  tolerations:
    - operator: Exists
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 1000m
      memory: 768Mi
longhornDriver:
  nodeSelector:
    kubernetes.io/os: linux
  tolerations:
    - operator: Exists
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 500m
      memory: 512Mi
