apiVersion: v1
kind: Secret
metadata:
  name: apps-gitops-repo-mtls
  namespace: apps-system
  labels:
    argocd.argoproj.io/secret-type: repository
    cryptophys.io/flux-managed: "true"
stringData:
  type: git
  url: http://platform-code-forge-gitea-http.gitops-system.svc.cluster.local:3000/cryptophys-work/apps-gitops.git
  insecure: "true"
