apiVersion: v1
kind: Secret
metadata:
  name: argocd-secret
  namespace: apps-system
type: Opaque
data:
  admin.password: JDJ5JDEwJEtmWmRuQWpvMHNDcU13QkdILkQ2SU9oRTNkcTJIdFFYeG94aVhSSXU0QjRtRzI0LmhEWUwy
