apiVersion: v1
kind: Secret
metadata:
  name: argocd-admin-password-hash
  namespace: apps-system
  annotations:
    cryptophys.io/domain: platform
    cryptophys.io/component: argocd
    cryptophys.io/anti-regression: "true"
type: Opaque
data:
  admin.password: JDJ5JDEwJEtmWmRuQWpvMHNDcU13QkdILkQ2SU9oRTNkcTJIdFFYeG94aVhSSXU0QjRtRzI0LmhEWUwy
