apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: apps-gitops-repo-headless
  namespace: apps-system
  annotations:
    cryptophys.io/domain: platform
    cryptophys.io/component: argocd
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: apps-gitops-repo-headless
    creationPolicy: Owner
    template:
      metadata:
        labels:
          argocd.argoproj.io/secret-type: repository
      data:
        type: git
        url: "http://gitops-gitea-http.gitops-system.svc.cluster.local:3000/cryptophys-work/apps-gitops.git"
        insecure: "true"
        username: "{{ .username }}"
        password: "{{ .password }}"
  data:
    - secretKey: username
      remoteRef:
        key: apps/gitea/admin
        property: username
    - secretKey: password
      remoteRef:
        key: apps/gitea/admin
        property: password
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: apps-gitops-repo-internal
  namespace: apps-system
  annotations:
    cryptophys.io/domain: platform
    cryptophys.io/component: argocd
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: apps-gitops-repo-internal
    creationPolicy: Owner
    template:
      metadata:
        labels:
          argocd.argoproj.io/secret-type: repository
      data:
        type: git
        url: "http://gitea-http-internal.gitops-system.svc.cluster.local:3000/cryptophys-work/apps-gitops.git"
        insecure: "true"
        username: "{{ .username }}"
        password: "{{ .password }}"
  data:
    - secretKey: username
      remoteRef:
        key: apps/gitea/admin
        property: username
    - secretKey: password
      remoteRef:
        key: apps/gitea/admin
        property: password
