apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: linkerd-control-plane
  namespace: linkerd
spec:
  releaseName: linkerd-control-plane
  interval: 1h
  timeout: 20m
  dependsOn:
    - name: linkerd-crds
      namespace: linkerd
  valuesFrom:
    - kind: Secret
      name: linkerd-control-plane-values
      valuesKey: values.yaml
  chart:
    spec:
      chart: linkerd-control-plane
      version: 1.16.11
      sourceRef:
        kind: HelmRepository
        name: linkerd
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
