apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  name: external-secrets-baseline
  namespace: external-secrets
spec:
  endpointSelector: {}
  egress:
  - toEntities: [kube-apiserver, host, cluster]
  - toEndpoints:
    - matchLabels:
        app.kubernetes.io/instance: vault
        app.kubernetes.io/name: vault
        component: server
        io.kubernetes.pod.namespace: vault-system
    toPorts:
    - ports:
      - port: "8200"
        protocol: TCP
  - toEndpoints:
    - matchLabels:
        k8s-app: kube-dns
        kubernetes.io/metadata.name: kube-system
    toPorts:
    - ports: [{port: "53", protocol: ANY}]
