apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: external-secrets
  namespace: external-secrets
spec:
  interval: 1h
  install:
    disableWait: true
  upgrade:
    disableWait: true
    preserveValues: false
  chart:
    spec:
      chart: external-secrets
      version: 0.9.11
      sourceRef:
        kind: HelmRepository
        name: external-secrets
        namespace: flux-system
  values:
    installCRDs: true
    replicaCount: 2
    nodeSelector:
      kubernetes.io/os: linux
      workload.cryptophys.work/platform: "true"
    affinity:
      nodeAffinity: null
    tolerations:
      - key: cryptophys.io/pool
        operator: Equal
        value: platform-ha
        effect: NoSchedule
      - key: ray-head
        operator: Exists
        effect: NoSchedule
      - key: node.cilium.io/agent-not-ready
        operator: Exists
        effect: NoSchedule
    webhook:
      replicaCount: 2
      nodeSelector:
        kubernetes.io/os: linux
        workload.cryptophys.work/platform: "true"
      affinity:
        nodeAffinity: null
      tolerations:
        - key: cryptophys.io/pool
          operator: Equal
          value: platform-ha
          effect: NoSchedule
        - key: ray-head
          operator: Exists
          effect: NoSchedule
        - key: node.cilium.io/agent-not-ready
          operator: Exists
          effect: NoSchedule
    certController:
      nodeSelector:
        kubernetes.io/os: linux
        workload.cryptophys.work/platform: "true"
      affinity:
        nodeAffinity: null
      tolerations:
        - key: cryptophys.io/pool
          operator: Equal
          value: platform-ha
          effect: NoSchedule
        - key: ray-head
          operator: Exists
          effect: NoSchedule
        - key: node.cilium.io/agent-not-ready
          operator: Exists
          effect: NoSchedule
