apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: vault-system
resources:
  - vault.yaml
  - vault__auto-unseal-controller.yaml
  - vault__unseal-keys-secret.yaml
  - vault-injector-cert.yaml
configMapGenerator:
  - name: vault-policy-hcl
    options:
      disableNameSuffixHash: true
      labels:
        app.kubernetes.io/name: vault-policy-hcl
        cryptophys.io/component: vault-policy
        cryptophys.io/managed-by: flux
    files:
      - external-secrets-kv2-read.hcl=policies/external-secrets-kv2-read.hcl
      - platform-kv2-bootstrap-write.hcl=policies/platform-kv2-bootstrap-write.hcl
      - vault-ui-operator-read.hcl=policies/vault-ui-operator-read.hcl
