apiVersion: v1
kind: Secret
metadata:
  name: vault-unseal-keys
  namespace: vault-system
  labels:
    cryptophys.io/component: vault
    cryptophys.io/managed-by: flux
stringData:
  key1: inzES7TCAT/1Ps/8q+VdxhdavEZO/gNjEB3CVUWm+bw4
  key2: 30tmNqmjQpu+5Mft3fFMlZTaCe7sne2InAwo4hxxjEb+
  key3: i3LPwLzxyYdaG89I9vNrcXqnvhfB0PemtMGm26g7rQ/7
type: Opaque
