apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: managednode.kubernetes.cryptophys.work
  labels:
    tier: platform
spec:
  compositeTypeRef:
    apiVersion: cryptophys.work/v1alpha1
    kind: XManagedNode
  resources:
  - name: node-labeler
    base:
      apiVersion: kubernetes.crossplane.io/v1alpha1
      kind: Object
      spec:
        forProvider:
          manifest:
            apiVersion: v1
            kind: Node
            metadata:
              name: ""
              labels:
                "cryptophys.io/tier": "platform"
            spec:
              taints: []
        providerConfigRef:
          name: local-kubernetes-provider
    patches:
    # Node name from claim name
    - fromFieldPath: "metadata.labels[crossplane.io/claim-name]"
      toFieldPath: "spec.forProvider.manifest.metadata.name"
    # Tier label
    - fromFieldPath: "spec.tier"
      toFieldPath: "spec.forProvider.manifest.metadata.labels[cryptophys.io/tier]"
    # Custom labels
    - fromFieldPath: "spec.customLabels"
      toFieldPath: "spec.forProvider.manifest.metadata.labels"
      policy:
        mergeOptions:
          appendSlice: true
    # Taints
    - fromFieldPath: "spec.taints"
      toFieldPath: "spec.forProvider.manifest.spec.taints"
      policy:
        fromFieldPath: Optional
