apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xlonghornreleases.cryptophys.work
spec:
  group: cryptophys.work
  names:
    kind: XLonghornRelease
    plural: xlonghornreleases
  claimNames:
    kind: LonghornRelease
    plural: longhornreleases
  versions:
  - name: v1alpha1
    served: true
    referenceable: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              defaultReplicaCount:
                type: integer
                minimum: 1
                maximum: 5
                default: 2
              taintToleration:
                type: string
              storageOverProvisioningPercentage:
                type: integer
                minimum: 1
                maximum: 200
                default: 50
              storageMinimalAvailablePercentage:
                type: integer
                minimum: 1
                maximum: 95
                default: 50
              concurrentReplicaRebuildPerNodeLimit:
                type: integer
                minimum: 1
                maximum: 10
                default: 2
              guaranteedInstanceManagerCPU:
                type: number
                minimum: 0
                maximum: 4
                default: 0.25
              systemManagedComponentsNodeSelector:
                type: string
                default: ""
              managerResources:
                type: object
                properties:
                  requests:
                    type: object
                    properties:
                      cpu:
                        type: string
                      memory:
                        type: string
                  limits:
                    type: object
                    properties:
                      cpu:
                        type: string
                      memory:
                        type: string
