apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: crossplane-provider-kubernetes-cnpg-editor
  namespace: postgresql-system
  annotations:
    cryptophys.io/domain: platform
    cryptophys.io/component: crossplane
    cryptophys.io/managed-by: flux
rules:
  - apiGroups:
      - postgresql.cnpg.io
    resources:
      - clusters
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: crossplane-provider-kubernetes-cnpg-editor
  namespace: postgresql-system
  annotations:
    cryptophys.io/domain: platform
    cryptophys.io/component: crossplane
    cryptophys.io/managed-by: flux
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: crossplane-provider-kubernetes-cnpg-editor
subjects:
  - apiGroup: rbac.authorization.k8s.io
    kind: Group
    name: system:serviceaccounts:crossplane-system
