apiVersion: v1
kind: Secret
metadata:
  name: apps-gitops-repo-mtls
  namespace: apps-system
  labels:
    argocd.argoproj.io/secret-type: repository
    cryptophys.io/flux-managed: "true"
stringData:
  type: git
  url: https://giteainternal.cryptophys.work/cryptophys-work/apps-gitops.git
  insecure: "false"
