apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: cryptophys-work-staging
  namespace: flux-system

resources:
  - ../../base

components:
  - ../../components/staging

commonLabels:
  environment: staging
  cluster: cryptophys-work
