apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - aide-flux-protection-policy.yaml
  - cloudnative-pg-policy-exception.yaml
  - flux-controllers-policy-exception.yaml
  - longhorn-policy-exception.yaml
  - postgres-apps-ha-policy-exception.yaml
  - cp-restriction-policy.yaml
  - security-observability-exception.yaml
  - stale-apps-ha-pods-policy-exception.yaml
  - tekton-pipelines-policy-exception.yaml
