apiVersion: v1
kind: Namespace
metadata:
  name: cqls-compute
  labels:
    cryptophys.io/domain: cqls
    cryptophys.io/system: compute
    cryptophys.io/node-class: nexus-hpc
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/warn: restricted
    cryptophys.io/pool: platform-ha
