apiVersion: v1
kind: Namespace
metadata:
  name: apps-system
---
apiVersion: v1
kind: Namespace
metadata:
  name: cert-manager
---
apiVersion: v1
kind: Namespace
metadata:
  name: external-secrets
---
apiVersion: v1
kind: Namespace
metadata:
  name: gatekeeper-system
---
apiVersion: v1
kind: Namespace
metadata:
  name: gitops-system
---
apiVersion: v1
kind: Namespace
metadata:
  name: ingress-system
  labels:
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/audit: privileged
    pod-security.kubernetes.io/warn: privileged
---
apiVersion: v1
kind: Namespace
metadata:
  name: kyverno-system
---
apiVersion: v1
kind: Namespace
metadata:
  name: longhorn-system
  labels:
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/audit: privileged
    pod-security.kubernetes.io/warn: privileged
---
apiVersion: v1
kind: Namespace
metadata:
  name: metallb-system
  labels:
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/audit: privileged
    pod-security.kubernetes.io/warn: privileged
---
apiVersion: v1
kind: Namespace
metadata:
  name: observability-system
---
apiVersion: v1
kind: Namespace
metadata:
  name: postgresql-system
---
apiVersion: v1
kind: Namespace
metadata:
  name: registry-system
---
apiVersion: v1
kind: Namespace
metadata:
  name: spire-system
  labels:
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/audit: privileged
    pod-security.kubernetes.io/warn: privileged
---
apiVersion: v1
kind: Namespace
metadata:
  name: vault-system
---
apiVersion: v1
kind: Namespace
metadata:
  name: minio-system
---
apiVersion: v1
kind: Namespace
metadata:
  name: velero-system
---
apiVersion: v1
kind: Namespace
metadata:
  name: security-system
---
apiVersion: v1
kind: Namespace
metadata:
  name: crossplane-system
