apiVersion: v1
kind: Namespace
metadata:
  name: apps-user
  labels:
    app.kubernetes.io/created-by: aide
    cryptophys.io/domain: apps
---
apiVersion: v1
kind: Namespace
metadata:
  name: default
  labels:
    app.kubernetes.io/created-by: aide
    cryptophys.io/domain: default
---
apiVersion: v1
kind: Namespace
metadata:
  name: facilitator
  labels:
    app.kubernetes.io/created-by: aide
    cryptophys.io/domain: facilitator
---
apiVersion: v1
kind: Namespace
metadata:
  name: image-factory
  labels:
    app.kubernetes.io/created-by: aide
    cryptophys.io/domain: image-factory
    cryptophys.io/node-class: nexus-hpc
---
apiVersion: v1
kind: Namespace
metadata:
  name: mesh-system
  labels:
    app.kubernetes.io/created-by: aide
    cryptophys.io/domain: mesh
---
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring-core
  labels:
    app.kubernetes.io/created-by: aide
    cryptophys.io/domain: monitoring
---
apiVersion: v1
kind: Namespace
metadata:
  name: orchestrator
  labels:
    app.kubernetes.io/created-by: aide
    cryptophys.io/domain: orchestrator
    kagenti-enabled: "true"
---
apiVersion: v1
kind: Namespace
metadata:
  name: platform-ui
  labels:
    app.kubernetes.io/created-by: aide
    cryptophys.io/domain: platform-ui
---
apiVersion: v1
kind: Namespace
metadata:
  name: tekton-system
  labels:
    app.kubernetes.io/created-by: aide
    cryptophys.io/domain: tekton
---
apiVersion: v1
kind: Namespace
metadata:
  name: trustedledger
  labels:
    app.kubernetes.io/created-by: aide
    cryptophys.io/domain: trustedledger
