apiVersion: v1
kind: Namespace
metadata:
  name: default
  labels:
    app.kubernetes.io/created-by: aide
    cryptophys.io/domain: default
---
apiVersion: v1
kind: Namespace
metadata:
  name: mesh-system
  labels:
    app.kubernetes.io/created-by: aide
    cryptophys.io/domain: mesh
