apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: argocd
  namespace: apps-system
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: HTTP
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - argocd.cryptophys.work
      secretName: cryptophys-wildcard-tls
  rules:
    - host: argocd.cryptophys.work
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: argocd-server
                port:
                  number: 80
