apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: vault
  namespace: vault-secrets
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: HTTP
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - vault.cryptophys.work
      secretName: cryptophys-wildcard-tls
  rules:
    - host: vault.cryptophys.work
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: vault
                port:
                  number: 8200
