apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - gateway-class.yaml
  - n8n-netpol.yaml
  - longhorn-oauth2-proxy.yaml
  - externalsecret-vault-ui-basic-auth.yaml
  - ingress-vault.yaml
  - ingress-hubble-ui.yaml
  - ingress-longhorn-ui.yaml
  - ingress-argocd.yaml
