apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - placeholder-configmap.yaml
  - ingress-vault.yaml
  - ingress-hubble-ui.yaml
  - ingress-longhorn-ui.yaml
  - ingress-headlamp.yaml
