apiVersion: apps/v1
kind: Deployment
metadata:
  name: crossplane-rbac-manager
  namespace: crossplane-system
spec:
  selector:
    matchLabels:
      app: crossplane-rbac-manager
      release: crossplane
  template:
    metadata:
      labels:
        app: crossplane-rbac-manager
        release: crossplane
    spec:
      nodeSelector:
        kubernetes.io/os: linux
      tolerations:
        - key: cryptophys.io/pool
          operator: Equal
          value: platform-ha
          effect: NoSchedule
        - key: ray-head
          operator: Exists
          effect: NoSchedule
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              preference:
                matchExpressions:
                  - key: accepts-platform-workloads
                    operator: In
                    values:
                      - "true"
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: workload.cryptophys.work/platform
                    operator: In
                    values:
                      - "true"
