apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: crossplane
  namespace: crossplane-system
spec:
  interval: 1h
  releaseName: crossplane
  chart:
    spec:
      chart: crossplane
      version: 1.18.2
      sourceRef:
        kind: HelmRepository
        name: crossplane
        namespace: flux-system
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
  postRenderers:
  - kustomize:
      patches:
      - target:
          kind: ValidatingWebhookConfiguration
          name: crossplane
        patch: |
          - op: replace
            path: /webhooks/0/failurePolicy
            value: Ignore
          - op: replace
            path: /webhooks/1/failurePolicy
            value: Ignore
      - target:
          kind: ValidatingWebhookConfiguration
          name: crossplane-no-usages
        patch: |
          - op: replace
            path: /webhooks/0/failurePolicy
            value: Ignore
  values:
    replicas: 1
    deploymentStrategy: RollingUpdate
    nodeSelector:
      kubernetes.io/os: linux
      workload.cryptophys.work/apps-core: "true"
    tolerations:
      - key: cryptophys.io/role
        operator: Equal
        value: llm-inference
        effect: NoSchedule
      - key: cryptophys.io/storage-only
        operator: Exists
        effect: NoSchedule
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: kubernetes.io/hostname
              operator: NotIn
              values:
              - thalamus-217-76-59-241
              - cerebellum-161-97-117-96
              - synapse-161-97-136-251
    resources:
      requests:
        cpu: 10m
        memory: 96Mi
      limits:
        cpu: 500m
        memory: 512Mi
