apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: external-secrets
  namespace: external-secrets
spec:
  interval: 1h
  chart:
    spec:
      chart: external-secrets
      version: 0.9.11
      sourceRef:
        kind: HelmRepository
        name: external-secrets
        namespace: flux-system
  values:
    installCRDs: true
    replicaCount: 2
    podAnnotations:
      cryptophys.io/redeploy-token: "2026-04-12-eso-vault-path-refresh"
    nodeSelector:
      kubernetes.io/os: linux
      workload.cryptophys.work/platform: "true"
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: kubernetes.io/hostname
                  operator: In
                  values:
                    - nexus-144-91-103-10
                    - cerebellum-161-97-117-96
      podAntiAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchLabels:
                  app.kubernetes.io/instance: external-secrets
                  app.kubernetes.io/name: external-secrets
              topologyKey: kubernetes.io/hostname
    tolerations:
      - key: cryptophys.io/pool
        operator: Exists
        effect: NoSchedule
      - key: node.cilium.io/agent-not-ready
        operator: Exists
        effect: NoSchedule
    webhook:
      replicaCount: 2
      podAnnotations:
        cryptophys.io/redeploy-token: "2026-04-12-eso-vault-path-refresh"
      nodeSelector:
        kubernetes.io/os: linux
        workload.cryptophys.work/platform: "true"
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: In
                    values:
                      - nexus-144-91-103-10
                      - cerebellum-161-97-117-96
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchLabels:
                    app.kubernetes.io/instance: external-secrets
                    app.kubernetes.io/name: external-secrets-webhook
                topologyKey: kubernetes.io/hostname
      tolerations:
        - key: cryptophys.io/pool
          operator: Exists
          effect: NoSchedule
        - key: node.cilium.io/agent-not-ready
          operator: Exists
          effect: NoSchedule
    certController:
      podAnnotations:
        cryptophys.io/redeploy-token: "2026-04-12-eso-vault-path-refresh"
      nodeSelector:
        kubernetes.io/os: linux
        workload.cryptophys.work/platform: "true"
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: In
                    values:
                      - nexus-144-91-103-10
                      - cerebellum-161-97-117-96
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchLabels:
                    app.kubernetes.io/instance: external-secrets
                    app.kubernetes.io/name: external-secrets-cert-controller
                topologyKey: kubernetes.io/hostname
      tolerations:
        - key: cryptophys.io/pool
          operator: Exists
          effect: NoSchedule
        - key: node.cilium.io/agent-not-ready
          operator: Exists
          effect: NoSchedule
