apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: ingress-gateway
  namespace: ingress-system
  annotations:
    reconcile.fluxcd.io/requestedAt: "1776348140"
spec:
  interval: 1h
  chart:
    spec:
      chart: ingress-nginx
      version: 4.14.1
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
        namespace: flux-system
  postRenderers:
    - kustomize:
        patches:
          - target:
              kind: DaemonSet
              name: ingress-gateway-ingress-nginx-controller
            patch: |
              apiVersion: apps/v1
              kind: DaemonSet
              metadata:
                name: ingress-gateway-ingress-nginx-controller
              spec:
                template:
                  spec:
                    tolerations:
                      - operator: Exists
  values:
    controller:
      kind: DaemonSet
      priorityClassName: cryptophys-platform-critical
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      config:
        allow-snippet-annotations: "true"
        annotations-risk-level: Critical
        client-header-buffer-size: 64k
        large-client-header-buffers: "16 128k"
      extraEnvs:
        - name: CRYPTOPHYS_INGRESS_ROLLOUT_AT
          value: "1776492350"
      extraArgs:
        default-ssl-certificate: ingress-system/platform-wildcard-tls
        healthz-port: "11054"
        profiling: "false"
        profiler-port: "0"
      livenessProbe:
        httpGet:
          port: 11054
      readinessProbe:
        httpGet:
          port: 11054
      metrics:
        port: 11054
      resources:
        requests:
          cpu: 50m
          memory: 128Mi
        limits:
          cpu: 500m
          memory: 256Mi
      nodeSelector:
        kubernetes.io/os: linux
      tolerations:
        - operator: Exists
      updateStrategy:
        type: RollingUpdate
        rollingUpdate:
          maxUnavailable: 10
      admissionWebhooks:
        enabled: false
      service:
        type: LoadBalancer
        loadBalancerIP: "10.8.0.240"
