apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: ingress-gateway
  namespace: ingress-system
spec:
  interval: 1h
  chart:
    spec:
      chart: ingress-nginx
      version: 4.14.1
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
        namespace: flux-system
  values:
    controller:
      kind: Deployment
      replicaCount: 3
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      extraArgs:
        default-ssl-certificate: ingress-system/platform-wildcard-tls
        healthz-port: "11054"
        profiling: "false"
        profiler-port: "0"
      livenessProbe:
        httpGet:
          port: 11054
      readinessProbe:
        httpGet:
          port: 11054
      metrics:
        port: 11054
      strategy:
        type: RollingUpdate
        rollingUpdate:
          maxSurge: 1
          maxUnavailable: 1
      resources:
        requests:
          cpu: 100m
          memory: 128Mi
        limits:
          cpu: 500m
          memory: 512Mi
      nodeSelector:
        workload.cryptophys.work/apps-core: "true"
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app.kubernetes.io/component
                      operator: In
                      values:
                        - controller
                    - key: app.kubernetes.io/instance
                      operator: In
                      values:
                        - ingress-gateway
                topologyKey: kubernetes.io/hostname
      tolerations:
        - effect: NoSchedule
          key: node-role.kubernetes.io/control-plane
          operator: Exists
        - effect: NoSchedule
          key: node.kubernetes.io/memory-pressure
          operator: Exists
      service:
        type: LoadBalancer
    admissionWebhooks:
      enabled: false
