apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: ingress-gateway
  namespace: ingress-system
spec:
  interval: 1h
  chart:
    spec:
      chart: ingress-nginx
      version: 4.14.1
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
        namespace: flux-system
  values:
    controller:
      kind: DaemonSet
      priorityClassName: cryptophys-platform-critical
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      extraEnvs:
        - name: CRYPTOPHYS_INGRESS_ROLLOUT_AT
          value: "2026-03-31T14:03:08Z"
      extraArgs:
        default-ssl-certificate: ingress-system/platform-wildcard-tls
        healthz-port: "11054"
        profiling: "false"
        profiler-port: "0"
      livenessProbe:
        httpGet:
          port: 11054
      readinessProbe:
        httpGet:
          port: 11054
      metrics:
        port: 11054
      resources:
        requests:
          cpu: 50m
          memory: 128Mi
        limits:
          cpu: 500m
          memory: 256Mi
      nodeSelector:
        kubernetes.io/os: linux
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: cryptophys.io/platform-ha
                    operator: In
                    values:
                      - "true"
              - matchExpressions:
                  - key: apps-core-target
                    operator: In
                    values:
                      - apps-core
      tolerations:
        - effect: NoSchedule
          key: node-role.kubernetes.io/control-plane
          operator: Exists
        - effect: NoSchedule
          key: node.kubernetes.io/memory-pressure
          operator: Exists
        - effect: NoSchedule
          key: cryptophys.io/storage-only
          operator: Exists
        - effect: NoSchedule
          key: cryptophys.io/role
          operator: Exists
      updateStrategy:
        type: RollingUpdate
        rollingUpdate:
          maxUnavailable: 2
      admissionWebhooks:
        enabled: false
      service:
        type: LoadBalancer
        loadBalancerIP: "10.8.0.240"
