apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - crossplane-operator.yaml
  - crossplane-policy-exception.yaml
  - platform-resource-quota.yaml
  - cert-manager.yaml
  - external-secrets.yaml
  - ingress-nginx.yaml
  - ingress-emergency-proxy.yaml
  - ingress-nginx-network-policy.yaml
  - metrics-server.yaml
  - pdbs.yaml
  - envoy-gateway.yaml
  - cnpg.yaml
  - ingress-policy-exception.yaml
