apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cert-manager.yaml
  - external-secrets.yaml
  - ingress-nginx.yaml
  - ingress-nginx-network-policy.yaml
  - metrics-server.yaml
  - pdbs.yaml
  - envoy-gateway.yaml
  - cilium/release.yaml
