apiVersion: v1
kind: ResourceQuota
metadata:
  name: platform-safety-limit
  namespace: flux-system
spec:
  hard:
    requests.cpu: "2000m"
    requests.memory: "3Gi"
    limits.cpu: "4000m"
    limits.memory: "6Gi"
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: platform-safety-limit
  namespace: apps-system
spec:
  hard:
    requests.cpu: "2000m"
    requests.memory: "4Gi"
    limits.cpu: "4000m"
    limits.memory: "8Gi"
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: platform-safety-limit
  namespace: apps-core
spec:
  hard:
    requests.cpu: "4000m"
    requests.memory: "6Gi"
    limits.cpu: "8000m"
    limits.memory: "12Gi"
