apiVersion: v1
kind: ResourceQuota
metadata:
  name: platform-safety-limit
  namespace: flux-system
spec:
  hard:
    requests.cpu: "8000m"
    requests.memory: "12Gi"
    limits.cpu: "24000m"
    limits.memory: "24Gi"
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: platform-safety-limit
  namespace: apps-system
spec:
  hard:
    requests.cpu: "5000m"
    requests.memory: "8Gi"
    limits.cpu: "12000m"
    limits.memory: "16Gi"
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: platform-safety-limit
  namespace: apps-core
spec:
  hard:
    requests.cpu: "4000m"
    requests.memory: "10Gi"
    limits.cpu: "10000m"
    limits.memory: "20Gi"
