apiVersion: v1
kind: ResourceQuota
metadata:
  name: platform-safety-limit
  namespace: flux-system
spec:
  hard:
    requests.cpu: "1500m"
    requests.memory: "2Gi"
    limits.cpu: "3000m"
    limits.memory: "4Gi"
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: platform-safety-limit
  namespace: apps-system
spec:
  hard:
    requests.cpu: "1500m"
    requests.memory: "2Gi"
    limits.cpu: "3000m"
    limits.memory: "4Gi"
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: platform-safety-limit
  namespace: apps-core
spec:
  hard:
    requests.cpu: "1500m"
    requests.memory: "2.5Gi"
    limits.cpu: "3000m"
    limits.memory: "5Gi"
