apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: platform-observability-loki
  namespace: observability-system
spec:
  interval: 1h
  timeout: 15m
  install:
    disableWait: true
    remediation:
      retries: 3
  upgrade:
    disableWait: true
    remediation:
      retries: 3
  chart:
    spec:
      chart: loki-stack
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
  values:
    loki:
      enabled: true
      isDefault: false
      persistence:
        enabled: false
      image:
        repository: docker.io/grafana/loki
      nodeSelector:
        cryptophys.io/platform-ha: "true"
      tolerations:
        - key: cryptophys.io/pool
          operator: Equal
          value: platform-ha
          effect: NoSchedule
        - key: node.cilium.io/agent-not-ready
          operator: Exists
          effect: NoSchedule
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: node-role.kubernetes.io/control-plane
                    operator: DoesNotExist
      resources:
        requests:
          cpu: 100m
          memory: 256Mi
        limits:
          cpu: 500m
          memory: 1Gi
    promtail:
      enabled: false
    grafana:
      enabled: false
    prometheus:
      enabled: false
    fluent-bit:
      enabled: true
      tolerations:
        - key: node-role.kubernetes.io/control-plane
          operator: Exists
          effect: NoSchedule
        - key: cryptophys.io/storage-only
          operator: Exists
          effect: NoSchedule
        - key: cryptophys.io/role
          operator: Exists
          effect: NoSchedule
        - key: cryptophys.io/pool
          operator: Exists
          effect: NoSchedule
        - key: ray-cluster
          operator: Exists
          effect: NoSchedule
        - key: ray-head
          operator: Exists
          effect: NoSchedule
        - key: bridge-system
          operator: Exists
          effect: NoSchedule
        - key: dao-system
          operator: Exists
          effect: NoSchedule
        - key: node.kubernetes.io/memory-pressure
          operator: Exists
          effect: NoSchedule
      resources:
        requests:
          cpu: 25m
          memory: 32Mi
        limits:
          cpu: 100m
          memory: 128Mi
