apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: platform-observability-loki
  namespace: observability-system
spec:
  interval: 1h
  timeout: 15m
  install:
    disableWait: true
    remediation:
      retries: 3
  upgrade:
    disableWait: true
    remediation:
      retries: 3
  chart:
    spec:
      chart: loki-stack
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
  values:
    loki:
      enabled: true
      isDefault: false
      persistence:
        enabled: false
      image:
        repository: docker.io/grafana/loki
      tolerations:
        - key: node-role.kubernetes.io/control-plane
          operator: Exists
          effect: NoSchedule
      nodeSelector:
        cryptophys.io/tier: platform
      resources:
        requests:
          cpu: 50m
          memory: 128Mi
        limits:
          cpu: 250m
          memory: 512Mi
    promtail:
      enabled: false
    grafana:
      enabled: false
    prometheus:
      enabled: false
    fluent-bit:
      enabled: true
      tolerations:
        - key: node-role.kubernetes.io/control-plane
          operator: Exists
          effect: NoSchedule
        - key: cryptophys.io/storage-only
          operator: Exists
          effect: NoSchedule
        - key: cryptophys.io/role
          operator: Exists
          effect: NoSchedule
      resources:
        requests:
          cpu: 25m
          memory: 32Mi
        limits:
          cpu: 100m
          memory: 128Mi
