apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: security-trivy-operator
  namespace: security-system
spec:
  interval: 1h
  install:
    remediation:
      retries: 3
    createNamespace: false
    crds: CreateReplace
  upgrade:
    remediation:
      retries: 3
    crds: CreateReplace
  chart:
    spec:
      chart: trivy-operator
      sourceRef:
        kind: HelmRepository
        name: aquasecurity
        namespace: flux-system
  values:
    replicaCount: 1
    trivy:
      ignoreUnfixed: true
    serviceMonitor:
      enabled: true
    tolerations:
      - key: cryptophys.io/storage-only
        operator: Equal
        value: "true"
        effect: NoSchedule
    nodeSelector:
      cryptophys.io/node-role: storage-worker
      kubernetes.io/hostname: campus-173-212-221-185
    scanJob:
      nodeSelector:
        kubernetes.io/hostname: campus-173-212-221-185
      tolerations:
        - key: cryptophys.io/storage-only
          operator: Exists
          effect: NoSchedule
    resources:
      requests:
        cpu: 50m
        memory: 128Mi
      limits:
        cpu: 250m
        memory: 512Mi
