apiVersion: kyverno.io/v2
kind: PolicyException
metadata:
  name: trivy-operator-exception
  namespace: security-system
spec:
  exceptions:
    - policyName: cp-standard-naming-v1
      ruleNames:
        - validate-resource-name
    - policyName: cp-supplychain-registry-v1
      ruleNames:
        - restrict-image-registries
    - policyName: cp-security-hardening-v1
      ruleNames:
        - restrict-pod-security-standard
  match:
    any:
      - resources:
          kinds:
            - Pod
          namespaces:
            - security-system
          names:
            - "security-trivy-operator-*"
            - "trivy-server-*"
