apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: daemonset-linux-only-nodeselector
  annotations:
    policies.kyverno.io/title: DaemonSet only nodeSelector linux
    policies.kyverno.io/category: Node Placement
    policies.kyverno.io/severity: high
    policies.kyverno.io/description: >
      For DaemonSet pods in ingress-system and tetragon-system, remove any hardcoded
      nodeAffinity pinning and force nodeSelector kubernetes.io/os=linux.
spec:
  validationFailureAction: Audit
  background: true
  rules:
    - name: daemonset-force-linux-nodeselector-only
      match:
        any:
          - resources:
              kinds:
                - DaemonSet
              namespaceSelector:
                matchExpressions:
                  - key: kubernetes.io/metadata.name
                    operator: In
                    values:
                      - ingress-system
                      - tetragon-system
      mutate:
        patchesJson6902: |-
          - op: replace
            path: /spec/template/spec/affinity
            value: {}
          - op: replace
            path: /spec/template/spec/nodeSelector
            value:
              kubernetes.io/os: linux
          - op: replace
            path: /spec/template/spec/tolerations
            value:
              - operator: Exists
