apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: daemonset-linux-only-nodeselector
  annotations:
    policies.kyverno.io/title: DaemonSet only nodeSelector linux
    policies.kyverno.io/category: Node Placement
    policies.kyverno.io/severity: high
    policies.kyverno.io/description: >
      For DaemonSet pods in ingress-system and tetragon-system, remove any hardcoded
      nodeAffinity pinning and force nodeSelector kubernetes.io/os=linux.
spec:
  validationFailureAction: Audit
  background: true
  rules:
    - name: clear-daemonset-node-affinity
      match:
        any:
          - resources:
              kinds:
                - Pod
            namespaceSelector:
              matchExpressions:
                - key: kubernetes.io/metadata.name
                  operator: In
                  values:
                    - ingress-system
                    - tetragon-system
      preconditions:
        all:
          - key: "{{ request.object.metadata.ownerReferences[?kind=='DaemonSet'] | length(@) }}"
            operator: Equals
            value: 1
          - key: "{{ request.object.spec.affinity.nodeAffinity || 'null' }}"
            operator: NotEquals
            value: 'null'
      mutate:
        patchesJson6902: |-
          - op: replace
            path: /spec/affinity
            value: {}
          - op: replace
            path: /spec/nodeSelector
            value:
              kubernetes.io/os: linux
