apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: gatekeeper
  namespace: gatekeeper-system
spec:
  interval: 1h
  releaseName: gatekeeper
  chart:
    spec:
      chart: gatekeeper
      version: "3.21.1"
      sourceRef:
        kind: HelmRepository
        name: gatekeeper
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  postRenderers:
    - kustomize:
        patches:
          - target:
              kind: Deployment
            patch: |
              apiVersion: apps/v1
              kind: Deployment
              metadata:
                name: any
              spec:
                template:
                  spec:
                    nodeSelector:
                      kubernetes.io/hostname: campus-173-212-221-185
                      kubernetes.io/os: linux
          - target:
              kind: Job
            patch: |
              apiVersion: batch/v1
              kind: Job
              metadata:
                name: any
              spec:
                template:
                  spec:
                    nodeSelector:
                      kubernetes.io/hostname: campus-173-212-221-185
                      kubernetes.io/os: linux
  values:
    replicas: 1
    crds:
      nodeSelector:
        kubernetes.io/hostname: campus-173-212-221-185
    pdb:
      controllerManager:
        minAvailable: 1
