apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - baseline.yaml
  - cilium-baseline.yaml
  - gatekeeper-release.yaml
  - kyverno-release.yaml
  - cp-restriction-policy.yaml
