apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: cp-sync-cryptophys-wildcard-tls
spec:
  generateExisting: true
  rules:
    - name: sync-wildcard-tls
      match:
        any:
          - resources:
              kinds:
                - Namespace
              names:
                - gitea
                - ingress
                - kube-system
                - longhorn-system
                - platform-ui
                - vault-secrets
      generate:
        apiVersion: v1
        kind: Secret
        name: cryptophys-wildcard-tls
        namespace: "{{ request.object.metadata.name }}"
        synchronize: true
        clone:
          namespace: kube-system
          name: cryptophys-wildcard-tls
