apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: kyverno
  namespace: kyverno-system
spec:
  interval: 1h
  releaseName: kyverno
  chart:
    spec:
      chart: kyverno
      version: "3.5.3"
      sourceRef:
        kind: HelmRepository
        name: kyverno
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 3
    crds: CreateReplace
  upgrade:
    remediation:
      retries: 3
    crds: CreateReplace
  values:
    features:
      policyExceptions:
        enabled: true
    config:
      exceptionNamespace: kyverno-system
    admissionController:
      createSelfSignedCert: true
      replicas: 1
      extraArgs:
        forceFailurePolicyIgnore: "true"
      nodeSelector:
        cryptophys.io/tier: platform
      tolerations:
        - key: "node-role.kubernetes.io/control-plane"
          operator: "Exists"
          effect: "NoSchedule"
      resources:
        requests:
          cpu: "200m"
          memory: "512Mi"
        limits:
          cpu: "1000m"
          memory: "1Gi"
    backgroundController:
      replicas: 1
      nodeSelector:
        cryptophys.io/tier: platform
      tolerations:
        - key: "node-role.kubernetes.io/control-plane"
          operator: "Exists"
          effect: "NoSchedule"
      resources:
        requests:
          cpu: "200m"
          memory: "512Mi"
        limits:
          cpu: "1000m"
          memory: "1Gi"
    cleanupController:
      createSelfSignedCert: true
      replicas: 1
      nodeSelector:
        cryptophys.io/tier: platform
      tolerations:
        - key: "node-role.kubernetes.io/control-plane"
          operator: "Exists"
          effect: "NoSchedule"
      resources:
        requests:
          cpu: "200m"
          memory: "512Mi"
        limits:
          cpu: "1000m"
          memory: "1Gi"
    reportsController:
      replicas: 1
      nodeSelector:
        cryptophys.io/tier: platform
      tolerations:
        - key: "node-role.kubernetes.io/control-plane"
          operator: "Exists"
          effect: "NoSchedule"
      resources:
        requests:
          cpu: "200m"
          memory: "512Mi"
        limits:
          cpu: "1000m"
          memory: "1Gi"
