apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: 00-crds
  namespace: flux-system
spec:
  interval: 1h
  path: ./platform/infrastructure/crds
  prune: true
  sourceRef:
    kind: GitRepository
    name: platform-repo
