apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: 01-namespaces
  namespace: flux-system
spec:
  interval: 1h
  wait: true
  timeout: 5m
  path: ./platform/infrastructure/namespaces
  prune: true
  sourceRef:
    kind: GitRepository
    name: platform-repo
  dependsOn:
    - name: 00-crds
