apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
spec:
  interval: 1h
  path: ./platform/infrastructure/spire-tekton
  sourceRef:
    kind: GitRepository
    name: platform-repo
  suspend: false
  timeout: 10m
