apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: 36-gitea
  namespace: flux-system
spec:
  interval: 1h
  wait: true
  timeout: 30m
  path: ./platform/infrastructure/gitea
  prune: true
  sourceRef:
    kind: GitRepository
    name: platform-repo
  dependsOn:
    - name: 35-secrets
    - name: 30-storage
    - name: 10-controllers
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta2
      kind: HelmRelease
      name: platform-code-forge-gitea
      namespace: gitops-system
