apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: platform-metallb
  namespace: metallb-system
spec:
  releaseName: platform-metallb
  interval: 1h
  timeout: 15m
  suspend: false
  chart:
    spec:
      chart: metallb
      version: 0.13.12
      sourceRef:
        kind: HelmRepository
        name: metallb
        namespace: flux-system
  install:
    disableWait: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    disableWait: true
    remediation:
      retries: 3
  postRenderers:
  - kustomize:
      patches:
      - target:
          kind: ValidatingWebhookConfiguration
          name: metallb-webhook-configuration
        patch: |
          - op: replace
            path: /webhooks/0/failurePolicy
            value: Ignore
          - op: replace
            path: /webhooks/1/failurePolicy
            value: Ignore
          - op: replace
            path: /webhooks/2/failurePolicy
            value: Ignore
          - op: replace
            path: /webhooks/3/failurePolicy
            value: Ignore
          - op: replace
            path: /webhooks/4/failurePolicy
            value: Ignore
          - op: replace
            path: /webhooks/5/failurePolicy
            value: Ignore
          - op: replace
            path: /webhooks/6/failurePolicy
            value: Ignore
      - target:
          kind: DaemonSet
          name: platform-metallb-speaker
        patch: |
          apiVersion: apps/v1
          kind: DaemonSet
          metadata:
            name: platform-metallb-speaker
          spec:
            updateStrategy:
              rollingUpdate:
                maxUnavailable: 10
            template:
              spec:
                affinity: null
  values:
    crds:
      enabled: true
    controller:
      nodeSelector:
        workload.cryptophys.work/apps-core: "true"
      tolerations:
        - key: cryptophys.io/role
          operator: Exists
          effect: NoSchedule
        - key: cryptophys.io/storage-only
          operator: Exists
          effect: NoSchedule
    speaker:
      affinity: null
      excludeInterfaces:
        enabled: true
      frr:
        enabled: false
      tolerateMaster: true
      tolerations:
        - key: node-role.kubernetes.io/control-plane
          operator: Exists
          effect: NoSchedule
        - key: node-role.kubernetes.io/master
          operator: Exists
          effect: NoSchedule
        - key: cryptophys.io/storage-only
          operator: Exists
          effect: NoSchedule
        - key: cryptophys.io/pool
          operator: Exists
          effect: NoSchedule
        - key: ray-cluster
          operator: Exists
          effect: NoSchedule
        - key: ray-head
          operator: Exists
          effect: NoSchedule
        - key: bridge-system
          operator: Exists
          effect: NoSchedule
        - key: dao-system
          operator: Exists
          effect: NoSchedule
        - key: cryptophys.io/role
          operator: Exists
          effect: NoSchedule
        - key: node.kubernetes.io/memory-pressure
          operator: Exists
          effect: NoSchedule
        - key: node.kubernetes.io/unreachable
          operator: Exists
          effect: NoSchedule
        - key: node.kubernetes.io/unreachable
          operator: Exists
          effect: NoExecute
        - key: node.cilium.io/agent-not-ready
          operator: Exists
          effect: NoSchedule
