apiVersion: v1
kind: ConfigMap
metadata:
  name: spire-agent-config
  namespace: spire
data:
  agent.conf: |
    Agent {
      data_dir = "/run/spire/data"
      log_level = "INFO"
      server_address = "spire-server"
      server_port = "8081"
      socket_path = "/run/spire/sockets/agent.sock"
      trust_bundle_path = "/run/spire/config/bundle.crt"
      trust_domain = "cryptophys.work"
    }
    plugins {
      NodeAttestor "k8s_psat" {
        plugin_data {
          cluster = "cryptophys-genesis"
        }
      }
      KeyManager "memory" {
        plugin_data {
        }
      }
      WorkloadAttestor "k8s" {
        plugin_data {
          # Use the default configuration
        }
      }
    }
  bundle.crt: |
    -----BEGIN CERTIFICATE-----
    MIIDaTCCAlGgAwIBAgIQd1OxT3bZC6WMwXFIDy04qTANBgkqhkiG9w0BAQsFADA8
    MQswCQYDVQQGEwJJRDETMBEGA1UEChMKQ3J5cHRvcGh5czEYMBYGA1UEAxMPY3J5
    cHRvcGh5cy53b3JrMB4XDTI2MDIxMjExMjkzNVoXDTI2MDIxMzExMjk0NVowPDEL
    MAkGA1UEBhMCSUQxEzARBgNVBAoTCkNyeXB0b3BoeXMxGDAWBgNVBAMTD2NyeXB0
    b3BoeXMud29yazCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAN1fJch0
    vWxR0eTtMijbiUWP+NeA7BmaM8byTNXDQwF3T5twYv1y4DjpTdrxqu0fZwsjmWsF
    2eXJAAnqjyHGvc+Uh6aVbIcFLx9X3yeCl3gczTEygmAPOMhwnfjb6xC//nU/c+Sd
    lNMOiY2dzDQA01uGnibYfUKDUP57ps9ujfmxzsRzqavicrATmPBhrTJWU7UvJOb9
    6lYxPPPdOGgbAdFAm8WL2BXVpnay8jm1tvTV84n8TMDDfC+IYGAwfBPi4XvoZ2tg
    3HFhS85JNyGKNtYFqZ0Pu5uszuomDzItcYE8aoGcfoyB36f2cTQObv2/inx5n5L4
    0v6hPEqcGWjLKr8CAwEAAaNnMGUwDgYDVR0PAQH/BAQDAgEGMA8GA1UdEwEB/wQF
    MAMBAf8wHQYDVR0OBBYEFAJfTTXH1A9hcpCnccRkf4J0GIJVMCMGA1UdEQQcMBqG
    GHNwaWZmZTovL2NyeXB0b3BoeXMud29yazANBgkqhkiG9w0BAQsFAAOCAQEAmEbC
    PZ++gApIRiMvwYpSV7DGFaO9hYW/Eod/D5py/q9V7kdooDfpeFnVZvV6xvj/lGiC
    nmcejaRTLvuf9k5oCacjxH08xtdGPIk6BYHMNu5NLL+atVZMOQikZIF8p5Olqc0h
    rmCKOkHiXWa+BcZkWwnzM92PlgYS6Ettw2e2v5Zn7imYgletVbkCExZC/bwQEvdg
    Wvrc3HmYTZfP2d4gEbdyRBqp1PHFz3hkwGOf5zj0O6uUpgjicdTJ7mCDosa4fUuI
    dWxWTacmb+jLuSN0wIlD7raoqdxgYyJ2rTNgGLiItZoIRgaA0VNHhySxWJOHhPw/
    5kirIJjP9Mn3qIHgAQ==
    -----END CERTIFICATE-----
