apiVersion: v1
kind: ConfigMap
metadata:
  name: spire-agent-config
  namespace: spire-system
data:
  agent.conf: |
    Agent {
      data_dir = "/run/spire/data"
      log_level = "INFO"
      server_address = "spire-server"
      server_port = "8081"
      socket_path = "/run/spire/sockets/agent.sock"
      trust_bundle_path = "/run/spire/config/bundle.crt"
      trust_domain = "cryptophys.work"
    }
    plugins {
      NodeAttestor "k8s_psat" {
        plugin_data {
          cluster = "cryptophys-genesis"
        }
      }
      KeyManager "memory" {
        plugin_data {
        }
      }
      WorkloadAttestor "k8s" {
        plugin_data {
          # Use the default configuration
        }
      }
    }
  bundle.crt: |
    -----BEGIN CERTIFICATE-----
    MIIDaTCCAlGgAwIBAgIQRTDgSghRsRicrMzYO055ijANBgkqhkiG9w0BAQsFADA8
    MQswCQYDVQQGEwJJRDETMBEGA1UEChMKQ3J5cHRvcGh5czEYMBYGA1UEAxMPY3J5
    cHRvcGh5cy53b3JrMB4XDTI2MDIxMzAzMDI0OFoXDTI2MDIxNDAzMDI1OFowPDEL
    MAkGA1UEBhMCSUQxEzARBgNVBAoTCkNyeXB0b3BoeXMxGDAWBgNVBAMTD2NyeXB0
    b3BoeXMud29yazCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAOJk0nl3
    h4EI9pJWGF8kfHn/mxRy65dz2aAPRTwNTXfv/OM26qgoR/w9FepCnFWsshtzvspZ
    /uMPjmeNvz6fum8R9sFrWlxCdX5SgmKrhQUuwOYQVCjE9GXcE7t9j5ojbeKOcBlP
    lWxd19J5AD8MYYU6GuSCHM9ZxX/z8ErCcJEaqQJuEcwSd3wDbyS9pbMPv5Ib5J7i
    jCJvqB0G6yR0CJBsBL2OeOgq7FwkNLZQhNSEQIiEaJ+9TfPVZDbxPtG51Ik60MB8
    pGPR4sT9yUWGW1fgit1s5HcWabiu38jNEYo4dumAnDgWocU3wnFTl1OVOUO4mhP0
    2nqU73KZuYs7uqMCAwEAAaNnMGUwDgYDVR0PAQH/BAQDAgEGMA8GA1UdEwEB/wQF
    MAMBAf8wHQYDVR0OBBYEFLRpAnaElvSCAnC1D637QUZsTEBxMCMGA1UdEQQcMBqG
    GHNwaWZmZTovL2NyeXB0b3BoeXMud29yazANBgkqhkiG9w0BAQsFAAOCAQEAt8Xr
    iY/itz2B8ulN8y0Xd/Qd2tTMU3AAdRpuyAXRrMU4DH871wA1KT415PwvevfsrTxK
    gPRH0LVZj4WnRTkl7uhXqCS19EinUDOIzB//AkXvg0vGG1TXQFqQh7L23ElsterP
    o3zrzcxUv7Vdfq/fduJmRBAK4pjixfeWV8hN9bS9tG2nPmv6qVksQ2xFGgWOWHPU
    rLbLkqAeLGB6YS1/qYQP8UqAXJ/hcH2CTFjsut/boAmI49Dc0UcG5uY10T/y50QS
    t3a/+dnSuhZorHcKq6fuQIpb3L3HpRsXUCh95ojwZ8bA3/MpKLzUa61m8kmDxnP6
    uyMaI+p2HecG9ll5Ug==
    -----END CERTIFICATE-----
