apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - rbac.yaml
  - server-service.yaml
  - server-config.yaml
  - server.yaml
  - agent-config.yaml
  - agent.yaml
  - linkerd-registration.yaml
