apiVersion: spire.spiffe.io/v1alpha1
kind: ClusterSPIFFEID
metadata:
  name: linkerd-identity
spec:
  spiffeIDTemplate: "spiffe://cryptophys.work/linkerd-identity"
  podSelector:
    matchLabels:
      linkerd.io/control-plane-component: identity
  namespaceSelector:
    matchLabels:
      kubernetes.io/metadata.name: linkerd
