apiVersion: v1
kind: ConfigMap
metadata:
  name: spire-server-config
  namespace: spire-system
data:
  server.conf: |
    Server {
      bind_address = "0.0.0.0"
      bind_port = "8081"
      trust_domain = "cryptophys.work"
      data_dir = "/run/spire/data"
      log_level = "INFO"
      ca_key_type = "rsa-2048"
    }
    plugins {
      DataStore "sql" {
        plugin_data {
          database_type = "postgres"
          connection_string = "postgresql://spire@postgres-security-ha-rw.postgresql-system.svc.cluster.local:5432/spire"
        }
      }
      NodeAttestor "k8s_psat" {
        plugin_data {
          clusters = {
            "cryptophys-genesis" = {
              service_account_allow_list = ["spire-system:spire-agent"]
            }
          }
        }
      }
      KeyManager "disk" {
        plugin_data {
          keys_path = "/run/spire/data/keys.json"
        }
      }
    }
