apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cloudflare-token-secret.yaml
  - letsencrypt-issuer.yaml
  - cryptophys-wildcard-cert.yaml
  - sync-cert-to-vault-cronjob.yaml
