apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - kuberay-operator.yaml
  - ray-cluster.yaml
  - ray-cluster-warm-build.yaml
  - policy-exception.yaml
  - ray-netpol.yaml
  - ray-dashboard-ingress.yaml
