apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: 01-namespaces
  namespace: flux-system
  annotations:
    cryptophys.io/domain: platform
    cryptophys.io/layer: platform
    cryptophys.io/managed-by: flux
spec:
  suspend: false   # Unsuspend after 00-crds is Applied
  interval: 10m
  prune: false    # Never prune namespaces
  wait: false
  timeout: 5m
  path: ./platform/infrastructure/namespaces
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: 00-crds
