apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: 11-controllers
  namespace: flux-system
spec:
  suspend: true
  interval: 1h
  wait: true
  timeout: 30m
  path: ./platform/infrastructure/controllers
  prune: false
  sourceRef:
    kind: GitRepository
    name: 11-controllers
  dependsOn:
    - name: 11-controllers
    - name: 11-controllers
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta2
      kind: HelmRelease
      name: 11-controllers
      namespace: kube-system
    - apiVersion: helm.toolkit.fluxcd.io/v2beta2
      kind: HelmRelease
      name: 11-controllers
      namespace: cert-manager
    - apiVersion: helm.toolkit.fluxcd.io/v2beta2
      kind: HelmRelease
      name: 11-controllers
      namespace: external-secrets
    - apiVersion: helm.toolkit.fluxcd.io/v2beta2
      kind: HelmRelease
      name: 11-controllers
      namespace: ingress-system
