apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: 12-storage
  namespace: flux-system
spec:
  suspend: true
  interval: 1h
  wait: true
  timeout: 30m
  path: ./platform/infrastructure/storage
  prune: false
  sourceRef:
    kind: GitRepository
    name: 12-storage
  dependsOn:
    - name: 12-storage
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta2
      kind: HelmRelease
      name: 12-storage
      namespace: longhorn-system
