apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: 15-policy
  namespace: flux-system
  annotations:
    cryptophys.io/domain: platform
    cryptophys.io/managed-by: flux
spec:
  suspend: true
  interval: 1h
  prune: false
  wait: true
  timeout: 10m
  path: ./platform/infrastructure/policy
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: 01-namespaces
    - name: 11-controllers
