apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: 20-certificates
  namespace: flux-system
  annotations:
    cryptophys.io/domain: platform
    cryptophys.io/managed-by: flux
    reconcile.fluxcd.io/requestedAt: "2026-04-11T11:42:00Z"
spec:
  suspend: false
  interval: 1h
  prune: true
  wait: false
  timeout: 10m
  path: ./platform/infrastructure/certificates
  sourceRef:
    kind: GitRepository
    name: platform-repo
  dependsOn:
    - name: 11-controllers
    - name: 31-secrets
