apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: platform-repo
  namespace: flux-system
spec:
  suspend: true
  interval: 1h
  wait: true
  timeout: 10m
  path: ./platform/infrastructure/dns
  prune: false
  sourceRef:
    kind: GitRepository
    name: platform-repo
  dependsOn:
    - name: platform-repo
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: platform-repo
      namespace: kube-system
