apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: 42-argocd
  namespace: flux-system
spec:
  suspend: true
  interval: 1h
  wait: false
  timeout: 30m
  path: ./platform/infrastructure/argocd
  prune: false
  sourceRef:
    kind: GitRepository
    name: 42-argocd
  dependsOn:
    - name: 42-argocd
    - name: 42-argocd
    - name: 42-argocd
