apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: 45-observability
  namespace: flux-system
spec:
  suspend: true
  interval: 1h
  wait: true
  timeout: 10m
  path: ./platform/infrastructure/observability
  prune: false
  sourceRef:
    kind: GitRepository
    name: 45-observability
  dependsOn:
    - name: 45-observability
    - name: 45-observability
