apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: 60-ray
  namespace: flux-system
  annotations:
    cryptophys.io/domain: platform
    cryptophys.io/managed-by: flux
spec:
  suspend: true
  interval: 1h
  prune: false
  wait: true
  timeout: 20m
  path: ./platform/infrastructure/ray
  sourceRef:
    kind: GitRepository
    name: platform-repo
  dependsOn:
    - name: 11-controllers
    - name: 12-storage
