apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: platform-backup-minio-credentials
  namespace: minio
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: platform-backup-minio-credentials
    creationPolicy: Owner
    template:
      type: Opaque
  data:
    - secretKey: rootUser
      remoteRef:
        key: platform/backup/minio
        property: rootUser
    - secretKey: rootPassword
      remoteRef:
        key: platform/backup/minio
        property: rootPassword
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: platform-backup-velero-credentials
  namespace: velero
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: platform-backup-velero-credentials
    creationPolicy: Owner
    template:
      type: Opaque
  data:
    - secretKey: cloud
      remoteRef:
        key: platform/backup/velero
        property: cloud
