apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - storageclass-longhorn-backup.yaml
  - minio-release.yaml
  - minio-console-ui.yaml
  - velero-release.yaml
  - ingress-minio-console.yaml
  - ingress-minio-s3.yaml
  - policy-exception.yaml
  - velero-policy-exception.yaml
  - backup-secrets.yaml
  # velero-schedules.yaml is in 50-backup-crs (needs Velero CRDs)
