apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - minio-release.yaml
  - velero-release.yaml
  - velero-schedules.yaml
  - ingress-minio-console.yaml
  - policy-exception.yaml
  - velero-policy-exception.yaml
