apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: platform-backup-minio
  namespace: minio
spec:
  interval: 1h
  timeout: 10m
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  chart:
    spec:
      chart: minio
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  values:
    mode: standalone
    auth:
      rootUser: velero
      rootPassword: "N8q!m2Xz7P4vA9sK"
    defaultBuckets: velero
    persistence:
      enabled: true
      storageClass: longhorn
      size: 50Gi
    resources:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        cpu: 1000m
        memory: 1Gi
