apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: platform-backup-velero
  namespace: velero-system
spec:
  interval: 1h
  timeout: 20m
  install:
    timeout: 20m
    remediation:
      retries: 3
  upgrade:
    timeout: 20m
    remediation:
      retries: 3
  chart:
    spec:
      chart: velero
      sourceRef:
        kind: HelmRepository
        name: vmware-tanzu
        namespace: flux-system
  values:
    configuration:
      backupStorageLocation:
      - name: default
        provider: aws
        bucket: velero
        default: true
        accessMode: ReadWrite
        config:
          region: us-east-1
          s3ForcePathStyle: true
          s3Url: http://platform-backup-minio.minio-system.svc.cluster.local:9000
    initContainers:
    - name: velero-plugin-for-aws
      image: velero/velero-plugin-for-aws:v1.11.0
      imagePullPolicy: IfNotPresent
      volumeMounts:
      - mountPath: /target
        name: plugins
    resources:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        cpu: 500m
        memory: 512Mi
    credentials:
      existingSecret: platform-backup-velero-credentials
      useSecret: true
    deployNodeAgent: false
    snapshotsEnabled: false
    upgradeCRDs: false
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: node-role.kubernetes.io/control-plane
              operator: DoesNotExist
    tolerations: []
    livenessProbe:
      httpGet:
        path: /healthz
        port: http
      initialDelaySeconds: 120
      periodSeconds: 30
      timeoutSeconds: 5
      failureThreshold: 3
    readinessProbe:
      httpGet:
        path: /metrics
        port: http
      initialDelaySeconds: 60
      periodSeconds: 10
      timeoutSeconds: 5
      failureThreshold: 3
