apiVersion: v1
kind: ServiceAccount
metadata:
  name: cloudflared
  namespace: cloudflare-tunnel
  labels:
    app.kubernetes.io/instance: cloudflared
    app.kubernetes.io/managed-by: flux
    app.kubernetes.io/name: cloudflared
    app.kubernetes.io/part-of: cryptophys-edge
    cryptophys.io/domain: platform
    cryptophys.io/component: cloudflared
    cryptophys.io/managed-by: flux
    cryptophys.io/layer: platform
