apiVersion: longhorn.io/v1beta2
kind: Node
metadata:
  name: campus-212-47-66-101
  namespace: longhorn-system
  labels:
    cryptophys.io/domain: platform
    cryptophys.io/component: longhorn-node-campus
    cryptophys.io/managed-by: flux
    cryptophys.io/layer: platform
spec:
  name: campus-212-47-66-101
  allowScheduling: false
  disks:
    default-disk-080600000000:
      allowScheduling: false
      diskDriver: ""
      diskType: filesystem
      evictionRequested: true
      path: /var/lib/longhorn/
      storageReserved: 17179869184
      tags: []
  evictionRequested: true
