apiVersion: longhorn.io/v1beta2
kind: Node
metadata:
  name: nexus-144-91-103-10
  namespace: longhorn-system
  labels:
    cryptophys.io/domain: platform
    cryptophys.io/component: longhorn-node-nexus
    cryptophys.io/managed-by: flux
    cryptophys.io/layer: platform
spec:
  name: nexus-144-91-103-10
  allowScheduling: true
  disks:
    default-disk-080600000000:
      allowScheduling: false
      diskDriver: ""
      diskType: filesystem
      evictionRequested: false
      path: /var/lib/longhorn/
      storageReserved: 21474836480
      tags: []
    data-disk-1901e1e1c520:
      allowScheduling: true
      diskDriver: ""
      diskType: filesystem
      evictionRequested: false
      path: /var/mnt/longhorn-data/
      storageReserved: 21474836480
      tags: []
  evictionRequested: false
