apiVersion: longhorn.io/v1beta2
kind: Node
metadata:
  name: cerebrum-157-173-120-200
  namespace: longhorn-system
  labels:
    cryptophys.io/domain: platform
    cryptophys.io/component: longhorn-node-cerebrum
    cryptophys.io/managed-by: flux
    cryptophys.io/layer: platform
spec:
  name: cerebrum-157-173-120-200
  allowScheduling: true
  disks:
    default-disk-080600000000:
      allowScheduling: true
      diskDriver: ""
      diskType: filesystem
      evictionRequested: false
      path: /var/lib/longhorn/
      storageReserved: 10737418240
      tags: []
  evictionRequested: false
