apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - platform__database_harbor_registry_bootstrap_es.yaml
  - platform__database_postgres_apps_ha.yaml
  - platform__database_postgres_apps_primary_realign.yaml
  - platform__database_postgres_security_ha.yaml
  - postgres-trustedledger-ha.yaml
  - platform__database_postgres_registry_ha.yaml
