apiVersion: v1
kind: Secret
metadata:
  name: policy-reporter-ui-basic-auth
  namespace: kyverno
type: Opaque
stringData:
  auth: "policyadmin:$2y$05$CG7UtWb25rCvH9nAeG75yeah/a9E3Wp5554wRO2E8i2qQ8oyAdRW."
