apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: platform-metallb-pool
  namespace: metallb-system
spec:
  addresses:
    - 10.8.0.240-10.8.0.250
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: platform-metallb-pool
  namespace: metallb-system
spec:
  ipAddressPools:
    - platform-metallb-pool
  interfaces:
    - ens18
