apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: vault-backend
  annotations:
    cryptophys.io/redeploy-token: "2026-04-12-vault-store-refresh"
    cryptophys.io/vault-eso-policy-source: "ConfigMap vault-system/vault-policy-hcl key external-secrets-kv2-read.hcl (policy name external-secrets)"
spec:
  provider:
    vault:
      server: http://vault.vault-system.svc:8200
      path: secret
      version: v2
      auth:
        tokenSecretRef:
          name: vault-eso-token
          key: token
          namespace: external-secrets
