apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: vault-backend
spec:
  provider:
    vault:
      server: http://vault-active.vault-system.svc:8200
      path: secret
      version: v2
      auth:
        tokenSecretRef:
          name: vault-eso-token
          key: token
          namespace: external-secrets
