apiVersion: external-secrets.io/v1beta1
kind: ClusterExternalSecret
metadata:
  name: harbor-pull-secret
spec:
  # Replicate harbor-pull-secret into every namespace
  # except kube-system, gitops-system, and argocd-system
  externalSecretName: harbor-pull-secret
  namespaceSelector:
    matchExpressions:
      - key: kubernetes.io/metadata.name
        operator: NotIn
        values:
          - kube-system
          - gitops-system
          - apps-system
          - flux-system
  refreshTime: 1h
  externalSecretSpec:
    secretStoreRef:
      name: vault-backend
      kind: ClusterSecretStore
    target:
      name: harbor-pull-secret
      template:
        type: kubernetes.io/dockerconfigjson
        data:
          .dockerconfigjson: |
            {
              "auths": {
                "registry.cryptophys.work": {
                  "username": "admin", # gitleaks:allow
                  "password": "{{ .password }}", # gitleaks:allow
                  "auth": "{{ printf "%s:%s" "admin" .password | b64enc }}"
                },
                "registry.cryptophys.work/library": {
                  "username": "admin", # gitleaks:allow
                  "password": "{{ .password }}", # gitleaks:allow
                  "auth": "{{ printf "%s:%s" "admin" .password | b64enc }}"
                },
                "registry.cryptophys.work/docker-proxy": {
                  "username": "admin", # gitleaks:allow
                  "password": "{{ .password }}", # gitleaks:allow
                  "auth": "{{ printf "%s:%s" "admin" .password | b64enc }}"
                }
              }
            }
    data:
      - secretKey: password
        remoteRef:
          key: apps/harbor/admin
          property: password
