apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cloudflared-credentials
  namespace: cloudflare-tunnel
  labels:
    app.kubernetes.io/name: cloudflared
    app.kubernetes.io/part-of: cryptophys-edge
    cryptophys.io/domain: platform
    cryptophys.io/component: cloudflared
    cryptophys.io/managed-by: flux
    cryptophys.io/layer: platform
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: cloudflared-credentials
    creationPolicy: Owner
  data:
    - secretKey: credentials_json
      remoteRef:
        key: platform/cloudflare/tunnel
        property: credentials_json
    - secretKey: tunnel_id
      remoteRef:
        key: platform/cloudflare/tunnel
        property: tunnel_id
