apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cryptophys-wildcard-tls
  namespace: gitops-system
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: cryptophys-wildcard-tls
    creationPolicy: Owner
    template:
      type: kubernetes.io/tls
      data:
        tls.crt: "{{ .tlscrt | b64dec }}"
        tls.key: "{{ .tlskey | b64dec }}"
  data:
  - secretKey: tlscrt
    remoteRef:
      key: platform/tls/cryptophys-wildcard
      property: tls.crt
  - secretKey: tlskey
    remoteRef:
      key: platform/tls/cryptophys-wildcard
      property: tls.key
