apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: gitea-ui-admin
  namespace: gitops-system
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: gitea-ui-admin
    creationPolicy: Owner
  data:
    - secretKey: username
      remoteRef:
        key: apps/gitea/ui-admin
        property: username
    - secretKey: password
      remoteRef:
        key: apps/gitea/ui-admin
        property: password
