apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: grafana-admin-credentials
  namespace: observability-system
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: grafana-admin-credentials
    creationPolicy: Owner
    template:
      data:
        admin-user: "{{ index . \"admin-user\" }}" # gitleaks:allow
        admin-password: "{{ index . \"admin-password\" }}" # gitleaks:allow
  data:
    - secretKey: admin-user
      remoteRef:
        key: apps/grafana/admin
        property: username
    - secretKey: admin-password
      remoteRef:
        key: apps/grafana/admin
        property: password
