apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: gitea-mirror-token
  namespace: gitops-system
  labels:
    cryptophys.io/domain: platform
    cryptophys.io/component: gitea-mirror
    cryptophys.io/managed-by: flux
    cryptophys.io/layer: platform
  annotations:
    cryptophys.io/contract: contract.platform.gitea.v1
    cryptophys.io/anti-regression: "true"
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: gitea-mirror-token
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: token
      remoteRef:
        key: apps/gitea/mirror-token
        property: token
    - secretKey: user
      remoteRef:
        key: apps/gitea/mirror-token
        property: user
