apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: registry-ci-credentials
  namespace: gitea
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: registry-ci-credentials
    creationPolicy: Owner
  data:
    - secretKey: username
      remoteRef:
        key: apps/registry/ci
        property: username
    - secretKey: password
      remoteRef:
        key: apps/registry/ci
        property: password
