apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: linkerd-control-plane-values
  namespace: linkerd
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: linkerd-control-plane-values
    creationPolicy: Owner
  data:
    - secretKey: values.yaml
      remoteRef:
        key: apps/linkerd/helm-values
        property: values_yaml
