apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - bootstrap-secrets.yaml
  - clustersecretstore-vault.yaml
  - externalsecret-gitea-admin-secret.yaml
  - externalsecret-gitea-helm-values.yaml
  - externalsecret-gitea-ops.yaml
  - externalsecret-registry-ci.yaml
  - externalsecret-wildcard-tls.yaml
  - externalsecret-grafana-admin.yaml
