apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - bootstrap-secrets.yaml
  - clustersecretstore-vault.yaml
  - externalsecret-cloudflared.yaml
  - externalsecret-gitea-admin-secret.yaml
  - externalsecret-gitea-helm-values.yaml
  - externalsecret-gitea-ops.yaml
  #- externalsecret-gitea-mirror-token.yaml
  - externalsecret-registry-ci.yaml
  - externalsecret-wildcard-tls.yaml
  - externalsecret-grafana-admin.yaml
  - externalsecret-harbor-admin.yaml
  - clusterexternalsecret-harbor-pull-secret.yaml
  - github-repo-auth-sync.yaml
